-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 23:31:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`category_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category_video` (
  `idcategory_video` INT NOT NULL,
  `category_video` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategory_video`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`videos_youtube`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`videos_youtube` (
  `id` INT NOT NULL,
  `code` VARCHAR(200) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  `description` VARCHAR(3000) NULL,
  `category_video` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videos_youtube_category_video_idx` (`category_video` ASC) VISIBLE,
  CONSTRAINT `fk_videos_youtube_category_video`
    FOREIGN KEY (`category_video`)
    REFERENCES `mydb`.`category_video` (`idcategory_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
